main: com.minebone.tnttag.core.TNTTag
version: 2.0-BETA1
name: TNTTag
api-version: 1.13

commands:
  tnttag:
    description: All commands for TNT Tag.
  tag:
    description: All commands for TNT Tag.